In [1]:
import numpy as np
np.__version__

'1.18.1'

In [9]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
a1=np.arange(21)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [11]:
#2.呈上題，將以上數列取出偶數。
a2=np.arange(0,20,2)
a2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
#3.呈1題，將數列取出3的倍數。
a3=np.arange(0,20,3)
a3

array([ 0,  3,  6,  9, 12, 15, 18])