In [193]:
import numpy as np
np.__version__

'1.18.1'

In [194]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
arr_inv = np.linalg.inv(array1)
print('反矩陣')
print(arr_inv)
print('反矩陣X原矩陣')
print(arr_inv@array1)

反矩陣
[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
反矩陣X原矩陣
[[1. 0.]
 [0. 1.]]


In [195]:
#2. 運用上列array計算特徵值、特徵向量?
u,v=np.linalg.eig(array1)
print('特徵值')
print(u)
print('特徵向量')
print(v)

特徵值
[13.  2.]
特徵向量
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [196]:
#3. 運用上列array計算SVD?
u, s, vh = np.linalg.svd(array1)
print('u = \n %s \ns = \n %s \nvh = \n %s'%(u,s,vh))

u = 
 [[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]] 
s = 
 [13.94721714  1.86417116] 
vh = 
 [[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
